[build]
buildCommand = "bun install && bun run build"

[deploy]
startCommand = "cd .medusa/server && bun install && bun run predeploy && bun run start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
